[package]
name = "amath"
version = "0.1.0"
authors = ["Colin Reeder <vpzomtrrfrt@gmail.com>"]

[dependencies]
lazy_static = "1.0.0"
lalrpop-util = "0.15.2"
regex = "1.0.0"

[build-dependencies]
lalrpop = "0.15.2"
